### ISSUE TITLE
SMB not showing on external starages

### ISSUE THREAD

**Issue by jacques24681** [mtthp/hassio-addons#1]
"smbclient" is not installed. Mounting of "SMB / CIFS", "SMB / CIFS using OC login" is not possible. Please ask your system administrator to install it.

How do I do this on hass.io?

**Comment by mtthp** [comment]
I'm sorry to hear this. I haven't got this issue on my setup which is installing hass.io using Docker on a Debian distribution.

I see you made a fork. Have you been able to resolve this ?

**Comment by jacques24681** [comment]
I tried, but I'm a newbie with this.  I ended up installing a ubuntu server and did a nextcloud install from scratch without docker and without snap.  Its working seperately now.  I dont know how to add smbcient to the docker file.  But anyways, keep up you good work.  thanx

**Comment by MephistoJB** [comment]
Hi Matthieu,

Same problem here.

![Bildschirmfoto 2020-04-25 um 09 01 05](https://user-images.githubusercontent.com/6490305/80273559-69d4da00-86d3-11ea-900a-fded91113c52.png)

I think, it must be added in the Dockerfile.

**Comment by mtthp** [comment]
I just got it working by doing the following : 
```bash
docker exec -it addon_local_nextcloud /bin/bash
apt-get update
apt-get install smbclient
```
You're right, it should be added to the image to avoid any trouble.

**Comment by jacques24681** [comment]
Thanx, will try it.

**Comment by MephistoJB** [comment]
Then you should change the row

`DEBIAN_FRONTEND=noninteractive apt-get install -y jq \`

in the Dockerfile to

`DEBIAN_FRONTEND=noninteractive apt-get install -y jq smbclient \`

@jacques24681 do you have any trouble with the installation like in #2?

**Comment by jacques24681** [comment]
Have not tried yet, but you can checkout the link from nextcloud where they explain what can be added to the dockerfile(looks like theres alot of modules not included in the dockerfile):  https://github.com/nextcloud/docker/blob/master/.examples/dockerfiles/full/apache/Dockerfile and https://github.com/nextcloud/docker/blob/master/.examples/dockerfiles/smb/apache/Dockerfile.  But I'm not sure how exactly to implement it.  If you can insert it, I'll test it.

**Comment by jacques24681** [comment]
Thanks, did not see. tried it, Its working 100% now.
