### ISSUE TITLE
JQ couldn't get installed via Dockerfile

### ISSUE THREAD

**Issue by MephistoJB** [mtthp/hassio-addons#2]
I don't know why, but I could get jq installed via Dockerfile. It seems, that there is no Internet connection. Any ideas?

**Comment by mtthp** [comment]
Hi @MephistoJB,

Haven't have any problem related to `jq`. In order to investigate a little more, what is your setup ?
Are you able to reach the internet inside a Docker container ?

**Comment by MephistoJB** [comment]
I am running Hassio on a VM. It’s a fresh install. I was able to run the apt-install inside the run.sh so it seems I have internetconnection after install.

**Comment by MephistoJB** [comment]
to be honest, I don't really know if it is because of the Internet Connection. After splitting the apt Commands I get the following error at the jq-installation row:


`The command '/bin/sh -c apt-get install -y -q jq' returned a non-zero code: 100`

Alltough not tried, I believe I would get the same error when adding the `apt-get install smbclient` of the SMB-Client Issue #1 

Do you run hassio on a pi?

**Comment by mtthp** [comment]
Yes, my setup run on Raspbian and Docker.

**Comment by MephistoJB** [comment]
So I have a different environment. Is there a way for me to give you additional Information for error tracking? Is there maybe a way to see the exact output of the command, which is stated above?

**Comment by mtthp** [comment]
Sure, just start a bash shell inside your container :
```bash
docker exec -it addon_local_nextcloud /bin/bash
```
and then try all the commands you want.

**Comment by MephistoJB** [comment]
without sudo I get:

`Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/addon_local_nextcloud/json: dial unix /var/run/docker.sock: connect: permission denied`

with sudo I get:

`Error: No such container: addon_local_nextcloud`

What am I doing wrong?

**Comment by mtthp** [comment]
`addon_local_nextcloud ` is just a name of the container. You can get yours by listing all the containers : 
```bash
docker ps -a
```
Alternatively, you can also pass the container id instead of its name.

**Comment by MephistoJB** [comment]
I found the error. It was my dns server at home. So now its working.

**Comment by xl0rnx** [comment]
I just run into the same error. Just wanted to post it because maybe some people looking for a fix. 

For me the Problem was: im running hass in a VM with a virtual drive. The virtual drive just didn't had enough free space to install all stuff. After expaning the drive all works like a charm.

So double check your free space ;)
