### ISSUE TITLE
docker images and ingress

### ISSUE THREAD

**Issue by sabuto** [mtthp/hassio-addons#6]
Hi, I was looking at this and was wondering how open you are to help? Would you be interested in adding the images to dockerhub so the end user doesn't have to build them? also would you mind if i added ingress to this? (or try to) great work so far :D

**Comment by mtthp** [comment]
Hello !

Sure, I'd love to get some help on this project ❤️ ! I was planning to add a pipeline and push the image to Docker hub but never had the time to commit myself to it.

Ingress should not be a problem but if you plan to use Nextcloud with another machine, you will have to map the port to the host anyway.

**Comment by sabuto** [comment]
That is a fair point i didn't consider. I have added the github workflow to a pr :)

**Comment by tyjtyj** [comment]
stuck at version 18.0.4 . occ upgrade dont work.. any work around ?

**Comment by mtthp** [comment]
Hey @tyjtyj 👋
I added some instructions on how to work around the database upgrade when you're skipping versions https://github.com/mtthp/hassio-addons/blob/master/nextcloud/TROUBLESHOOT.md#upgrade-nextcloud-database.
Hopefully, I will seriously commit to maintain this project and make a proper CI to upload the image to Dockerhub.

**Comment by tyjtyj** [comment]
i am getting this on V18.0.4

```
nextcloud:/share/nextcloud/html$ php occ upgrade
Nextcloud is already latest version

```

No idea how to upgrade from here. On the web updater, it shows 18.0.12 available but when i click update, it give error 404. 
Where do i miss ?

**Comment by mtthp** [comment]
Sure, that's because the `occ upgrade` only does the database migration. You need to upgrade the container first to get the new version of Nextcloud.

I pushed a new version of the add-on on the master branch, but no image has been published yet. You will need to build it locally (again).

**Comment by mtthp** [comment]
I'm closing this issue as a Github workflow has been successfully setup.
Feel free to open a new issue if anything goes wrong 😅
